# Generated by Django 4.0.3 on 2022-03-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=254, verbose_name='Наименование услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
