# Generated by Django 4.0.3 on 2022-03-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.IntegerField(null=True, verbose_name='Стоимость'),
        ),
    ]
