# Generated by Django 4.0.3 on 2022-04-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-id'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
